<?php

use MageMastery\Blog\Model\Post;
use MageMastery\Blog\ViewModel\PostViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Post $post */
/** @var PostViewModel $postViewModel */
/** @var Template $block */
/** @var Escaper $escaper */

$postViewModel = $block->getData('post_view_model');
$post = $block->getData('post');
?>
<?php if ($post->hasData('featured_image')): ?>
    <img src="<?= $escaper->escapeUrl($postViewModel->getFeaturedImageUrl($post)); ?>"
         alt="<?= $escaper->escapeHtmlAttr($post->getData('title')); ?>"
         loading="lazy" />
<?php endif; ?>
<a href="<?= $postViewModel->getPostUrl($post); ?>">
    <h3><?= $escaper->escapeHtml($post->getData('title')); ?></h3>
</a>
<div>
    <span class="author">Max Pronko</span>
    <span class="published-date"><?= $escaper->escapeHtml($block->formatDate($post->getData('creation_time'))); ?></span>
</div>
<p><?= $post->getData('content'); ?></p>
