<?php

use MageMastery\Blog\Model\Post;
use MageMastery\Blog\ViewModel\Post\PostView;
use Magento\Framework\View\Element\Template;

/** @var Post $post */
/** @var PostView $postView */
/** @var Template $block */

$postView = $block->getData('post_view_model');
$post = $postView->getPost();
?>
<h1><?= $post->getData('title'); ?></h1>
<p>
    <span class="author">Max Pronko</span>
    <span class="published-date"><?= $block->formatDate($post->getData('creation_time')); ?></span>
</p>
<p><?= $post->getData('content'); ?></p>
